# Generated by Django 5.1.1 on 2024-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_year', models.IntegerField()),
            ],
            options={
                'db_table': 'table_book',
            },
        ),
    ]
